---
apiVersion: v1
kind: Deployment
metadata:
  name: nginx-monitor
spec:
  replicas: 5
  selector:
    app: nginx-monitor
  template:
    metadata:
      name: nginx-monitor
      labels:
        app: nginx-monitor
    spec:
      containers:
      - name: nginx-monitor
        image: nginx
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: "config"
          mountPath: "/etc/nginx/nginx.conf"
          subPath: "nginx.conf"
      volumes:
        - name: "config"
          configMap:
            name: "nginxconfig"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: nginx-monitor
  name: nginx-monitor
spec:
  type: LoadBalancer
  selector:
    app: nginx-monitor
  ports:
  - name: http
    port: 80
    targetPort: 80
      